#!/bin/zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="alacritty,gh,nvim,zellij,zsh,utilities,starship"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
